# Configuración de la JVM para Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
# Paralelismo y caché
org.gradle.parallel=true
org.gradle.caching=true
# AndroidX
android.useAndroidX=true
# Nombres de recursos no transitivos (builds más rápidos)
android.nonTransitiveRClass=true
# Estilo de código Kotlin
kotlin.code.style=official
